ongoing work
Current test case state:
======================================================================
ERROR: test_frontpage (testManager.API)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testManager.py", line 187, in test_frontpage
      path=outfile)
        File "/Users/staffan/wds/ferenda/ferenda/manager.py", line 147, in frontpage
	    resourceloader=self.resourceloader,
	    NameError: name 'self' is not defined

======================================================================
ERROR: test_frontpage_staticsite (testManager.API)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testManager.py", line 209, in test_frontpage_staticsite
      staticsite=True)
        File "/Users/staffan/wds/ferenda/ferenda/manager.py", line 147, in frontpage
	    resourceloader=self.resourceloader,
	    NameError: name 'self' is not defined

======================================================================
ERROR: test_run_all_allmethods (testManager.Run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testManager.py", line 707, in test_run_all_allmethods
      got = manager.run(argv)
        File "/Users/staffan/wds/ferenda/ferenda/manager.py", line 396, in run
	    results[action] = run(argscopy, subcall=True)
	      File "/Users/staffan/wds/ferenda/ferenda/manager.py", line 378, in run
	          return frontpage(**args)
		    File "/Users/staffan/wds/ferenda/ferenda/manager.py", line 147, in frontpage
		        resourceloader=self.resourceloader,
			NameError: name 'self' is not defined

======================================================================
ERROR: test_run_makeresources_defaultconfig (testManager.Run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testManager.py", line 807, in test_run_makeresources_defaultconfig
      'sitename': 'Test'})
      TypeError: resource_extract() missing 1 required positional argument: 'params'

======================================================================
ERROR: test_run_single_allmethods (testManager.Run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testManager.py", line 754, in test_run_single_allmethods
      self.assertEqual(manager.run(argv),
        File "/Users/staffan/wds/ferenda/ferenda/manager.py", line 396, in run
	    results[action] = run(argscopy, subcall=True)
	      File "/Users/staffan/wds/ferenda/ferenda/manager.py", line 378, in run
	          return frontpage(**args)
		    File "/Users/staffan/wds/ferenda/ferenda/manager.py", line 147, in frontpage
		        resourceloader=self.resourceloader,
			NameError: name 'self' is not defined

======================================================================
ERROR: test_setup (testManager.Setup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/.pythonz/pythons/CPython-3.4.0/lib/python3.4/unittest/mock.py", line 1125, in patched
      return func(*args, **keywargs)
        File "/Users/staffan/wds/ferenda/test/testManager.py", line 236, in test_setup
	    argv=argv)
	      File "/Users/staffan/wds/ferenda/ferenda/manager.py", line 544, in setup
	          util.resource_extract('res/scripts/ferenda-build.py', buildscript)
		  TypeError: resource_extract() missing 2 required positional arguments: 'outfile' and 'params'

======================================================================
ERROR: test_files (testResources.BaseAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testResources.py", line 272, in test_files
      legacyapi=True).make(css=False, js=False, img=False, xml=False, api=True)
        File "/Users/staffan/wds/ferenda/ferenda/resources.py", line 62, in make
	    res['json'] = self.make_api_files()
	      File "/Users/staffan/wds/ferenda/ferenda/resources.py", line 303, in make_api_files
	          self.resourceloader.extractdir("ui", targetdir)
		    File "/Users/staffan/wds/ferenda/ferenda/resourceloader.py", line 153, in extractdir
		        shutil.copy2(src, dest)
			  File "/Users/staffan/.pythonz/pythons/CPython-3.4.0/lib/python3.4/shutil.py", line 244, in copy2
			      copyfile(src, dst, follow_symlinks=follow_symlinks)
			        File "/Users/staffan/.pythonz/pythons/CPython-3.4.0/lib/python3.4/shutil.py", line 108, in copyfile
				    with open(dst, 'wb') as fdst:
				    FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/sy/r4f01ykx7v31d8_0nmvsyc2r0000gn/T/tmp9_36iutq/data/rsrc/ui/bootstrap-modal.js'

======================================================================
ERROR: test_combining (testResources.Make)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testResources.py", line 111, in test_combining
      sitedescription="A non-default value").make(api=False)
        File "/Users/staffan/wds/ferenda/ferenda/resources.py", line 54, in make
	    res['css'] = self.make_css()
	      File "/Users/staffan/wds/ferenda/ferenda/resources.py", line 83, in make_css
	          'cssfiles', self.resourcedir + os.sep + 'css', combinefile, cssmin.cssmin)
		    File "/Users/staffan/wds/ferenda/ferenda/resources.py", line 202, in _make_files
		        urls.append(self._process_file(f, buf, filedir, repo.alias))
			  File "/Users/staffan/wds/ferenda/ferenda/resources.py", line 245, in _process_file
			      buf.write(fp.read())
			      TypeError: 'str' does not support the buffer interface

======================================================================
ERROR: test_highlighted_snippet (testWSGI.Search)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testWSGI.py", line 728, in test_highlighted_snippet
      status, headers, content = self.call_wsgi(self.env)
        File "/Users/staffan/wds/ferenda/test/testWSGI.py", line 126, in call_wsgi
	    for chunk in self.app(environ, start_response):
	      File "/Users/staffan/wds/ferenda/ferenda/wsgiapp.py", line 63, in __call__
	          return self.search(environ, start_response)
		    File "/Users/staffan/wds/ferenda/ferenda/wsgiapp.py", line 125, in search
		        resourceloader=self.resourceloader,
			AttributeError: 'WSGIApp' object has no attribute 'resourceloader'

======================================================================
ERROR: test_paged (testWSGI.Search)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testWSGI.py", line 762, in test_paged
      status, headers, content = self.call_wsgi(self.env)
        File "/Users/staffan/wds/ferenda/test/testWSGI.py", line 126, in call_wsgi
	    for chunk in self.app(environ, start_response):
	      File "/Users/staffan/wds/ferenda/ferenda/wsgiapp.py", line 63, in __call__
	          return self.search(environ, start_response)
		    File "/Users/staffan/wds/ferenda/ferenda/wsgiapp.py", line 125, in search
		        resourceloader=self.resourceloader,
			AttributeError: 'WSGIApp' object has no attribute 'resourceloader'

======================================================================
ERROR: test_search_multiple (testWSGI.Search)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testWSGI.py", line 671, in test_search_multiple
      status, headers, content = self.call_wsgi(self.env)
        File "/Users/staffan/wds/ferenda/test/testWSGI.py", line 126, in call_wsgi
	    for chunk in self.app(environ, start_response):
	      File "/Users/staffan/wds/ferenda/ferenda/wsgiapp.py", line 63, in __call__
	          return self.search(environ, start_response)
		    File "/Users/staffan/wds/ferenda/ferenda/wsgiapp.py", line 125, in search
		        resourceloader=self.resourceloader,
			AttributeError: 'WSGIApp' object has no attribute 'resourceloader'

======================================================================
ERROR: test_search_single (testWSGI.Search)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testWSGI.py", line 638, in test_search_single
      status, headers, content = self.call_wsgi(self.env)
        File "/Users/staffan/wds/ferenda/test/testWSGI.py", line 126, in call_wsgi
	    for chunk in self.app(environ, start_response):
	      File "/Users/staffan/wds/ferenda/ferenda/wsgiapp.py", line 63, in __call__
	          return self.search(environ, start_response)
		    File "/Users/staffan/wds/ferenda/ferenda/wsgiapp.py", line 125, in search
		        resourceloader=self.resourceloader,
			AttributeError: 'WSGIApp' object has no attribute 'resourceloader'

======================================================================
FAIL: test_run_makeresources (testManager.Run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testManager.py", line 775, in test_run_makeresources
      self.assertEqual(want, got)
      AssertionError: {'jso[81 chars]g': ['rsrc/img/test.png'], 'css': ['rsrc/css/t[85 chars]ml']} != {'jso[81 chars]g': [], 'css': [], 'js': [], 'xml': ['rsrc/resources.xml']}
      - {'css': ['rsrc/css/test.css', 'rsrc/css/other.css'],
      -  'img': ['rsrc/img/test.png'],
      -  'js': ['rsrc/js/test.js'],
      + {'css': [],
      +  'img': [],
      +  'js': [],
         'json': ['rsrc/api/context.json',
	             'rsrc/api/common.json',
		                 'rsrc/api/terms.json'],
				    'xml': ['rsrc/resources.xml']}

======================================================================
FAIL: test_filename (testResourceLoader.Main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/staffan/wds/ferenda/test/testResourceLoader.py", line 86, in test_filename
      self.resourceloader.filename("robots.txt"))
      AssertionError: 'ferenda/res/robots.txt' != '/Users/staffan/wds/ferenda/ferenda/res/robots.txt'
      - ferenda/res/robots.txt
      + /Users/staffan/wds/ferenda/ferenda/res/robots.txt

----------------------------------------------------------------------
Ran 431 tests in 31.790s

FAILED (failures=2, errors=12)
Python 3.4.0